[settings]
pipx_uvx = true

[tools]
"python" = "3.14.0"
"pipx:makejinja" = "2.8.1"
"aqua:budimanjojo/talhelper" = "3.0.41"
"aqua:cilium/cilium-cli" = "0.18.8"
"aqua:cli/cli" = "2.83.1"
"aqua:cloudflare/cloudflared" = "2025.11.1"
"aqua:cue-lang/cue" = "latest"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.45.5"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:kubernetes/kubectl" = "1.34.0"
"aqua:mikefarah/yq" = "4.50.1"
"aqua:siderolabs/talos" = "1.11.5"
"aqua:yannh/kubeconform" = "0.7.0"
"aqua:helm/helm" = "3.19.4"
"aqua:helmfile/helmfile" = "1.2.2"
"aqua:astral-sh/uv" = ["latest"]
"pipx:flux-local" = ["latest"]
