apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age1cdzkds0kys9q5r698hq2p2cj600zcvj4uhztgc800q59gsh53p3q93zpe9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRWVWVkpCQ2huMHF1QnRi
        MVBsMGNDV0hkQ3ZnUFBhRys1aEhWN2hlUTI4CnVQV2QySW5EaHVUWU8xZEVOM1Jm
        RmdabkpGdmZ3TFcvR0dtSU1vNzc1eFkKLS0tIHBYSEY1WHJsOGpvSlhyWmN5TUpv
        OExFV0R0b1d1VlJnS1ZocUptQUpzWGMKiq6fOjOr/utlAvyK3mbE4M7aMf/ux5P6
        BTGw1AQ7nX/7XFBkfSnjEILmL2n502WqIRyn7oiqDTA2iIg5EzoI+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T09:36:04Z"
  mac: ENC[AES256_GCM,data:LyAR/HjA+uxCMZPCEj82YtQtUsx9onk4pm7K7+Z3ymorEtzn1HgZbVB5Ebn55piwo0z9/n8yuXXFUfJQyZk/j9G5VwOuRUjEdWYoLOZI2yMkSQwKDjhcFe+jT74DxrA5pzsh/RqSkIF2HldYD8H4jMXpTqg17k/jmfw03NFLnZY=,iv:Hk9iLbDLXL/lp0272avF2BhJXqLi101Xep8Cf/tSW6o=,tag:D+SBcKW4J2s0FAqe6+90Wg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
