apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:TORsNuULkPcMJxVwHlr1g8Wtj880BzaxdJSfC/IZF/U=,iv:ylCbkO/a24U4X3U24TPt3wLebfzV9afQ5/hcQde28J4=,tag:1fK5+k4DnWzGv1XOIsGyCw==,type:str]
sops:
  age:
    - recipient: age1cdzkds0kys9q5r698hq2p2cj600zcvj4uhztgc800q59gsh53p3q93zpe9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVjJVMTFOb2dvbVRWb1pF
        ZVhrYXVnSHVmNlY5dW9VT0w2SmxVOVhuaW1ZCldsZVYwejRXKzlNUWgvOTZuZ1Rh
        SWowTkxNblJHTjhLRmxxeUY5ZStSak0KLS0tIElkZlA4N01tZUEvaE01ZVJTLzg1
        YVVsSnpYWHlMUjQwM0VSM3cybmNoUncK6necGSLPzK+HUVwuEuG2eyHyAVnqhscI
        EZp59Scbib7vmrhlHWcAYKP5wV98upTIvgcAilV2TG57guhqbWqMcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T09:36:04Z"
  mac: ENC[AES256_GCM,data:gv6Hcuxq2jAyEseiMLTcT0+XxezjpXVwc5FpoLF5vst6eTMJnXuKOOfJdY40mLzoGT41WERi61k7MSNljpBsPkWqh/OWCtABMFlTX35YOWnbhgrUZKL2AWVlmaM4F/WR8XM1AxI6n/uL8SbEOAD98PrO+UosWO5mXB1BSFLcmlc=,iv:pbzKM57oHMW6UDq2Lbhc6HAmKh8bIbrrg9xccEkXhWo=,tag:eVUbyJTMHBQ8vh0v4U9Stg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
