apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Nhpchjy//s5v6celYstGMCK3J2wh3RMSjpIhB/m+r+EWASD0y8bJ8cmCoZznxQVVtzVOnK605Yu4CEBUTgeuhLXajxaInaBcqxh2E2YfF2kOeT9vXK4Cw/Wjxowp8A4j9klUh9C5Oy5TPDUQ/f6tWIltYZXhhwDfb8NlQ3V41nOSHxJeFVXN5z0I/NrE/wGN6haEtLoalTj4EUmtNfvdU3rtjskZzF5WFSeYhjquNC1vIopG,iv:odRkRWHEWeBnYGk9GYcu0iEzr64hdrN4z3JyXee6GOc=,tag:oV0UJpnRgIVqhTrCFa+T4g==,type:str]
sops:
  age:
    - recipient: age1cdzkds0kys9q5r698hq2p2cj600zcvj4uhztgc800q59gsh53p3q93zpe9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTFZRQU9zZUhiRnVGK1dW
        dU4zUmx3clBmZitmWTJabklCaFY5alZDNm5ZCjBIR3hyL1BNeXV6RFdZcDAvRktQ
        UlFWV1hWbjZhUG55cE9Xd0dkdGptL2cKLS0tIFhFTkVrTGFQQ0M2a1d1NnhFUjgy
        UTN3Q05UWU9FTUtLc3ZONFl0RTVDdEEKsMJOlHquSxAudgd9tXyX5uKvEbEGl/ti
        ljVm593egXthta6nttjBZkWKSakibQBp+pMldHJlzNt9ZfmXmbgiHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T09:36:04Z"
  mac: ENC[AES256_GCM,data:8EYJKGMMoT9MaSnpUpLqHwdL/3wcbcFpjxsZIJ8H0BkUA0q/QQ0HZqr7HJIsdPjByG4n5LAx4TW+BKRxrPseW4dmEioRkHRLUddtwzdn+kjACZMi0hJDcusVpc5zkAJLYnZUh5GDAt9zZUhtECF4MzVg/EYaBF3gFIGVgojRpb8=,iv:xFEDrgNXAbkXh4RnhEA11o9d/qg2OEnl2Db1tIRQy30=,tag:SSmQuUuFZXv+8PkXnCINkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
