apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: truenas-backend-tls
  namespace: network
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: external-service-truenas
  tls:
    validation:
      skip: true
