---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: external-service-truenas
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443      
  type: ClusterIP