---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-secret
    creationPolicy: Owner
  data:
    - secretKey: pushover_api_token
      remoteRef:
        key: Pushover
        property: alertmanager_token
    - secretKey: pushover_api_userkey
      remoteRef:
        key: Pushover
        property: userkey_falk
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kube-prometheus-stack-secret
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      type: s3
      data:
        config:
          bucket: "{{ .s3_bucket }}"
          endpoint: "{{ .s3_endpoint }}"
          region: us-east-1
          access_key: "{{ .S3_ACCESS_KEY }}"
          secret_key: "{{ .S3_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: kube-prometheus-stack
    - extract:
        key: thanos

