---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret thanos-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      data:
        S3_BUCKET: thanos
        S3_HOST: minio.default:9000
        S3_ACCESS_KEY: "{{ .S3_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .S3_SECRET_KEY }}"
        S3_REGION: us-east-1
        TIMEZONE: "Europa/Berlin"
        TZ: "Europa/Berlin"
        HASS_BEARER_TOKEN: "{{ .HASS_BEARER_TOKEN }}"
        # Codeserver
        id_rsa: "{{ .ADMIN_SSH_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: home-assistant
    - extract:
        key: admin-user
